import { ApiProperty } from '@nestjs/swagger';
import { IsString } from 'class-validator';

export class SendLOSNotificationDto {
  @IsString()
  @ApiProperty()
  msisdn: string; // Note: including the +countryCode

  @IsString()
  @ApiProperty()
  content: string; // Note: The actual message content that is to be sent to the recipient

  @IsString()
  @ApiProperty()
  channel: string; // Note: Whether this is generated by LOS, LMS to be sent as SMS/InApp Notification/Email/ Push notification

  @IsString()
  @ApiProperty()
  event_name: string; // Note: The event for which this message is generated on the LOS, LMS side (can be 'Disbursal', 'Repayment', 'Reminder', 'Loan Closure',

  @IsString()
  @ApiProperty()
  event_date: string; // Note: the timestamp on the LOS, LMS side at which the event got generated.

  @IsString()
  @ApiProperty()
  txn_id: string; // Note: This is the unique ID for the generated event on the LOS, LMS side, which the MW is to store and refer to later / send back in its response to the LOS, LMS or refer to later while calling a 'webhook' API of the LOS, LMS
}
