export enum ApplicationStatus {
  RUN_INITIATED = 'RUN_INITIATED',
  LEAD_CREATED = 'LEAD_CREATED',
  LEAD_VERIFIED = 'LEAD_VERIFIED',
  LEAD_ENHANCED = 'LEAD_ENHANCED',
  CONFIRM_STUDENT_DETAILS = 'CONFIRM_STUDENT_DETAILS',
  APPLY_LOANS = 'APPLY_LOANS',
  SUBMIT_LOANS = 'SUBMIT_LOANS',
  REPAY_LOAN = 'REPAY_LOAN',
  GET_LOAN_LIST = 'GET_LOAN_LIST',
  LOAN_STATEMENT_DETAILS = 'LOAN_STATEMENT_DETAILS',
}
