export enum OtpAction {
  FORGOT_PIN = 'FORGOT_PIN',
  RESET_PIN = 'RESET_PIN',
  LOGIN = 'LOGIN',
  ADD_ALTERNATE_NUMBER = 'ADD_ALTERNATE_NUMBER',
  NEW_DEVICE_REGISTRATION = 'NEW_DEVICE_REGISTRATION',
}
